import { useEffect, useState } from "react";
import {
  api,
  type CaseArtifact,
  type Evidence,
  formatTime,
  type Narration,
  percent,
  rupees,
  type SourceRef,
  shortHash,
  type TransactionLabel,
} from "./api";

interface Props {
  alertId: string;
}

export function CaseView({ alertId }: Props) {
  const [artifact, setArtifact] = useState<CaseArtifact>();
  const [narration, setNarration] = useState<Narration>();
  const [truth, setTruth] = useState<TransactionLabel>();
  const [error, setError] = useState<string>();

  useEffect(() => {
    let cancelled = false;
    setArtifact(undefined);
    setNarration(undefined);
    setTruth(undefined);
    setError(undefined);

    api
      .case(alertId)
      .then(async (result) => {
        if (cancelled) return;
        setArtifact(result.artifact);
        setNarration(result.narration);
        const label = await api.truth(result.artifact.subject.txnId).catch(() => undefined);
        if (!cancelled) setTruth(label);
      })
      .catch((cause: Error) => {
        if (!cancelled) setError(cause.message);
      });

    return () => {
      cancelled = true;
    };
  }, [alertId]);

  if (error) return <p className="placeholder">{error}</p>;
  if (!artifact) return <p className="placeholder">Investigating…</p>;

  const probability = Number(artifact.fraudProbability);
  const contributionByCode = new Map(
    artifact.contributions.map((entry) => [entry.feature, Number(entry.logOdds)]),
  );
  const against = artifact.findings.filter((finding) => finding.direction === "inculpatory");
  const supporting = artifact.findings.filter((finding) => finding.direction === "exculpatory");

  return (
    <div>
      <div className="verdict-bar">
        <span className={`verdict-badge verdict-${artifact.action}`}>
          {artifact.action.toUpperCase()}
        </span>
        <div className="verdict-stat">
          <b>{percent(probability)}</b>
          <span>probability of fraud</span>
        </div>
        <div className="verdict-stat">
          <b>{rupees(artifact.expectedCostMinor)}</b>
          <span>expected cost of this action</span>
        </div>
        <div className="verdict-stat">
          <b>{artifact.evidence.length}</b>
          <span>evidence items</span>
        </div>
        {truth && (
          <span className={`truth ${truth.isFraud ? "truth-fraud" : "truth-legit"}`}>
            ground truth: {truth.isFraud ? `fraud · ${truth.variant}` : (truth.decoyKind ?? "legitimate")}
          </span>
        )}
      </div>

      {narration && (
        <section className="section">
          <h2>Summary</h2>
          <div className="narration">
            {narration.text}
            <div className="narration-source">
              generated by: {narration.source}
              {narration.source === "template" && " (no model configured — grounded by construction)"}
            </div>
            {narration.rejected.map((rejected) => (
              <div className="dropped" key={rejected.text}>
                dropped a sentence: {rejected.reason}
              </div>
            ))}
          </div>
        </section>
      )}

      <section className="section">
        <h2>Evidence against ({against.length})</h2>
        {against.length === 0 && <p className="note">No probe returned an inculpatory finding.</p>}
        {against.map((finding) => (
          <FindingRow
            key={finding.code}
            alertId={alertId}
            artifact={artifact}
            code={finding.code}
            summary={finding.summary}
            evidenceIds={finding.evidenceIds}
            contribution={contributionByCode.get(finding.code) ?? 0}
            direction="against"
          />
        ))}
      </section>

      <section className="section">
        <h2>Evidence in the customer's favour ({supporting.length})</h2>
        {supporting.length === 0 && (
          <p className="note">
            No exculpatory finding. Absence of history is not treated as innocence.
          </p>
        )}
        {supporting.map((finding) => (
          <FindingRow
            key={finding.code}
            alertId={alertId}
            artifact={artifact}
            code={finding.code}
            summary={finding.summary}
            evidenceIds={finding.evidenceIds}
            contribution={contributionByCode.get(finding.code) ?? 0}
            direction="for"
          />
        ))}
      </section>

      <ReplayPanel alertId={alertId} artifact={artifact} />
    </div>
  );
}

interface FindingProps {
  alertId: string;
  artifact: CaseArtifact;
  code: string;
  summary: string;
  evidenceIds: string[];
  contribution: number;
  direction: "against" | "for";
}

function FindingRow({
  alertId,
  artifact,
  code,
  summary,
  evidenceIds,
  contribution,
  direction,
}: FindingProps) {
  const [open, setOpen] = useState(false);
  const evidenceId = evidenceIds[0];
  const evidence = artifact.evidence.find((item) => item.evidenceId === evidenceId);
  const tone = contribution === 0 ? "none" : direction;

  return (
    <div className="finding">
      <button
        type="button"
        className="finding-head"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
      >
        <span className={`contribution ${tone}`}>
          {contribution > 0 ? "+" : ""}
          {contribution.toFixed(2)}
        </span>
        <span className="finding-summary">
          {summary}
          <span className="finding-code">
            {code}
            {contribution === 0 && " · no additional weight beyond correlated findings"}
          </span>
        </span>
        <span className="chev">{open ? "▲ hide evidence" : "▼ show evidence"}</span>
      </button>
      {open && evidence && <EvidencePanel alertId={alertId} evidence={evidence} />}
    </div>
  );
}

function EvidencePanel({ alertId, evidence }: { alertId: string; evidence: Evidence }) {
  const [records, setRecords] = useState<{ source: SourceRef; record: unknown }[]>();

  useEffect(() => {
    let cancelled = false;
    api
      .evidence(alertId, evidence.evidenceId)
      .then((result) => {
        if (!cancelled) setRecords(result.records);
      })
      .catch(() => {
        if (!cancelled) setRecords([]);
      });
    return () => {
      cancelled = true;
    };
  }, [alertId, evidence.evidenceId]);

  return (
    <div className="evidence">
      <div className="evidence-probe">
        {evidence.probe} · {evidence.subjectType} {evidence.subjectId}
        {evidence.fromMs !== null && evidence.toMs !== null && (
          <> · {formatTime(evidence.fromMs)} → {formatTime(evidence.toMs)}</>
        )}
      </div>

      <dl className="kv">
        {Object.entries(evidence.payload).map(([key, value]) => (
          <div key={key} style={{ display: "contents" }}>
            <dt>{key}</dt>
            <dd>{Array.isArray(value) ? value.join(", ") : String(value)}</dd>
          </div>
        ))}
      </dl>

      <div className="evidence-probe">
        source records ({evidence.sources.length}) — every one hashed at collection time
      </div>
      <div className="records">
        {(records ?? []).slice(0, 8).map(({ source, record }) => (
          <div className="record" key={`${source.table}:${source.id}`}>
            <div className="record-head">
              {source.table}:{source.id} · {shortHash(source.hash)}
            </div>
            <pre>{JSON.stringify(record)}</pre>
          </div>
        ))}
        {records === undefined && <div className="record">loading…</div>}
        {records && records.length > 8 && (
          <div className="record">
            <div className="record-head">…and {records.length - 8} more cited records</div>
          </div>
        )}
      </div>
    </div>
  );
}

function ReplayPanel({ alertId, artifact }: { alertId: string; artifact: CaseArtifact }) {
  const [result, setResult] = useState<Awaited<ReturnType<typeof api.replay>>>();
  const [busy, setBusy] = useState(false);

  const run = async () => {
    setBusy(true);
    try {
      setResult(await api.replay(alertId));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="section">
      <h2>Integrity</h2>
      <div className="chain">
        <div>
          case hash <b>{artifact.caseHash.replace("sha256:", "")}</b>
        </div>
        <div>
          model hash <b>{artifact.modelHash.replace("sha256:", "")}</b>
        </div>
        <div>
          world root <b>{artifact.worldRoot.replace("sha256:", "")}</b>
        </div>
        <div>
          subject record <b>{shortHash(artifact.subject.hash)}</b> ·{" "}
          {artifact.evidence.reduce((total, item) => total + item.sources.length, 0)} source records
          sealed
        </div>
      </div>

      <div className="actions" style={{ marginTop: 12 }}>
        <button type="button" className="btn" onClick={run} disabled={busy}>
          {busy ? "Replaying…" : "Replay this case"}
        </button>
        <span className="note" style={{ margin: 0 }}>
          Re-runs the sealed plan and recomputes every cited record's hash.
        </span>
      </div>

      {result && (
        <div className={`replay-result ${result.status === "verified" ? "replay-ok" : "replay-fail"}`}>
          {result.status === "verified"
            ? `VERIFIED\ncase hash reproduced exactly\n${result.recordsVerified} source records re-hashed and matched`
            : `${result.status === "integrity_failure" ? "INTEGRITY FAILURE" : "REPLAY MISMATCH"}\n${result.message}`}
        </div>
      )}
    </section>
  );
}
